/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#1000a9",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "secondary": "#c0c1ff",
        "on-primary-fixed-variant": "#004397",
        "on-surface-variant": "#c1c6d7",
        "primary": "#aec6ff",
        "inverse-on-surface": "#233143",
        "indigo-accent": "#4F46E5",
        "bg-slate": "#1E293B",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-surface": "#d4e4fa",
        "surface-container-lowest": "#010f1f",
        "on-background": "#d4e4fa",
        "error": "#ffb4ab",
        "tertiary": "#c3c6d3",
        "tertiary-fixed": "#dfe2ef",
        "surface-dim": "#051424",
        "tertiary-container": "#727682",
        "glass-fill": "rgba(15, 23, 42, 0.7)",
        "on-primary-container": "#ffffff",
        "outline": "#8b90a0",
        "on-tertiary-fixed": "#181b25",
        "outline-variant": "#414754",
        "bg-deep": "#0A0E17",
        "surface-container-highest": "#273647",
        "error-container": "#93000a",
        "surface-variant": "#273647",
        "surface-container-high": "#1c2b3c",
        "secondary-container": "#3131c0",
        "surface-container-low": "#0d1c2d",
        "inverse-surface": "#d4e4fa",
        "surface": "#051424",
        "surface-tint": "#aec6ff",
        "surface-bright": "#2c3a4c",
        "background": "#051424",
        "primary-fixed-dim": "#aec6ff",
        "on-secondary-fixed": "#07006c",
        "on-tertiary": "#2c303a",
        "inverse-primary": "#0059c5",
        "glass-stroke": "rgba(255, 255, 255, 0.08)",
        "surface-container": "#122131",
        "on-primary-fixed": "#001a43",
        "tertiary-fixed-dim": "#c3c6d3",
        "on-tertiary-fixed-variant": "#434751",
        "on-primary": "#002e6b",
        "primary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-container": "#b0b2ff",
        "electric-blue": "#0070F3",
        "primary-container": "#0070f3",
        "on-tertiary-container": "#ffffff",
        "secondary-fixed": "#e1e0ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "margin-desktop": "40px",
        "unit": "4px",
        "margin-mobile": "16px",
        "gutter": "24px",
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
